
language: python
python:
  - 3.6
  - 3.7-dev
git:
  depth: false
install:
  - pip install coveralls
  - pip install numpy matplotlib
script:
  - python test_ga.py
  - coveralls
branches:
  only:
    - master
notifications:
  email: false
after_sucess:
  - echo "Travis CI built!"
